server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.1.25:8082/realms/supreme
      client:
        provider:
          keycloak:
            issuer-uri: http://192.168.1.25:8082/realms/supreme
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: supreme-client
            client-secret: e8blJKB96rjzAAqkXnKT3eEQShW8OQjT
            scope: openid

#logging:
#  level:
#    org.springframework.security: TRACE